apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: GIT_URL
      type: string 
      default: https://github.com/jkapl/ci-cd-istio-tekton
    - name: REVISION
      type: string  
      default: master
  # resources: {}
  steps:
    - name: git-clone
      image: gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.12.1
      # workingDir: $(workspaces.source)
      securityContext:
        privileged: true
      script: |
        cd $(workspaces.source.path)
        rm -rf ci-cd-istio-tekton
        git clone -b "$(params.REVISION)" "$(params.GIT_URL)"
        cd ci-cd-istio-tekton
        RESULT_SHA="$(git rev-parse HEAD | tr -d '\n')"
        pwd
        echo -n "$RESULT_SHA"
  workspaces:
    - name: source
      description: Location of source code